### ISSUE TITLE
Receiving Error while running example/ion_bal.py

### ISSUE THREAD

**Issue by pritivish** [johnson-c/ColRadPy#4]
Hello, 
 I am trying to run ionization balance (time-independent  with metastable states) from file provided in example/ion_bal.py.
but I am receiving the following error

**../colradpy/colradpy_class.py:1094: RuntimeWarning: divide by zero encountered in double_scalars
  - self.data['atomic']['energy'][i]))
Traceback (most recent call last):
  File "ion_bal-1.py", line 86, in <module>
    ax1.plot(temp,ion.data['processed']['pops_ss'][0,0,:,1],label='be0, met0',color='b')
IndexError: too many indices for array**

I running with python3.6 as suggested. 

I am able to run the ionization balance using ADF11 files with only ground state. 

and i using the same ADS4 files as given in example.
Please suggest what could be the reson? 

Actually, I have fine structure resolved ionization and reconbination rates, finally I want to use those as input in this code.

**Comment by johnson-c** [comment]
This example had not been updated with the correct dictionary label for the time dependent population. It should be fixed with the current version of the example. It works for me now if you could check it works for you I'll close the issue.

**Comment by pritivish** [comment]
Dear Johnson, 

Thank you so much. :)
It's working now. 

However, there are lots of warning like 

/home/user/ColRadPy-master/examples/ion_bal.py:15: DeprecationWarning: object of type <class 'float'> cannot be safely interpreted as an integer.
  time = np.linspace(0,.01,1.e4) #solution time grid
../colradpy/colradpy_class.py:1094: RuntimeWarning: divide by zero encountered in double_scalars
  - self.data['atomic']['energy'][i]))
/usr/lib/python3/dist-packages/numpy/core/numeric.py:531: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/home/user/ColRadPy-master/examples/ion_bal.py:110: DeprecationWarning: object of type <class 'float'> cannot be safely interpreted as an integer.
  ion.solve_source(np.array([1,0,0,0,0,0,0]),np.array([1,0,0,0,0,0,0]),np.linspace(0,.06,1e3))
